/**
 * Mule Jive Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.jive;


import org.mule.tck.junit4.FunctionalTestCase;

import org.junit.Test;

/**Test for the {@link JiveModule}.
 * */
public class JiveSchemaTest extends FunctionalTestCase {
    @Override
    protected final String getConfigResources() {
        return "mule-config.xml";
    }

    /**Test the flow.
     * @throws Exception If flow fails
     * */
    @Test
    public final void testFlow() throws Exception
    {
    }

}
